const page = document.body.dataset.page || '';
const A = '../assets/';

const locations = {
  ratnagiri:{name:'Ratnagiri',address:'Behind Civil Hospital, Rajiwada, Ratnagiri, Maharashtra 415612',phones:['+91 96040 54834'],image:'ratnagiri-hospital-hd.png'},
  satara:{name:'Satara',address:'Sadarbazar, Guruwar Peth, Satara, Maharashtra 415002',phones:['+91 77159 08507','+91 99706 08139'],image:'satara-hospital-hd.png'},
  alibaug:{name:'Alibaug',address:'Civil Hospital, Alibag Beach Road, Limaye Wadi, Alibag, Maharashtra 402201',phones:['+91 72760 15041'],image:'civil-hospital-hd.png'},
  thane:{name:'Thane',address:'Near Utsal Road, Opposite Police Quarter, Tembhi Naka, Thane (W), Maharashtra 400601',phones:['+91 72760 15041'],image:'lab-interior-hd.png'},
  'pune-aundh':{name:'Pune Aundh',address:'Aundh Hospital Campus, Between Sanghvi Phata and Rakshak Chowk, Pune 411027',phones:['+91 97022 63697','+91 98506 44544'],image:'civil-hospital-hd.png'}
};

const routeName = page === 'book-an-appointment' ? 'Appointment' : page;
const active = (name) => routeName === name ? ' class="active"' : '';

const header = `
<a class="skip-link" href="#content">Skip to content</a>
<div class="service-notice" aria-label="Service schedule"><div class="notice-inner"><strong>Important service schedule</strong><span><b>Morning:</b> Government Service</span><span class="notice-divider" aria-hidden="true"></span><span><b>Evening:</b> Private Service</span></div></div>
<header class="site-header">
  <a class="brand" href="../" aria-label="Unique Care home"><img src="${A}logo.webp" alt="Unique Care"></a>
  <button class="menu-button" type="button" aria-expanded="false" aria-controls="main-navigation"><span></span><span></span><span></span><em>Main menu</em></button>
  <nav id="main-navigation" class="main-nav" aria-label="Main navigation">
    <a href="../">Home</a><a${active('services')} href="../services/">Services</a>
    <div class="presence"><button type="button" aria-expanded="false">Our Presence <img class="nav-arrow" src="${A}chevron.svg" alt=""></button><div class="presence-menu"><a href="../ratnagiri/">Ratnagiri</a><a href="../satara/">Satara</a><a href="../alibaug/">Alibaug</a><a href="../thane/">Thane</a><a href="../pune-aundh/">Pune Aundh</a></div></div>
    <a${active('about-us')} href="../about-us/">About Us</a><a${active('contact-us')} href="../contact-us/">Contact Us</a><a class="button header-cta" href="../book-an-appointment/">Make An Appointment</a>
  </nav>
</header>`;

const footer = `
<footer class="site-footer"><div class="footer-grid"><div><img src="${A}logo.webp" alt="Unique Care"><p>Advanced imaging. Compassionate care. Accurate results you can trust.</p></div><div><h2>Services</h2><a href="../mri-scan/">MRI Scan</a><a href="../ct-scan/">CT Scan</a><a href="../services/">All Services</a></div><div><h2>Company</h2><a href="../about-us/">About Us</a><a href="../testimonial/">Testimonials</a><a href="../contact-us/">Contact Us</a></div><div><h2>Contact</h2><a href="tel:+919850644544">+91 98506 44544</a><a href="mailto:ubercare@uber-india.com">ubercare@uber-india.com</a><p>Morning: Government<br>Evening: Private</p></div></div><div class="footer-bottom"><span>Copyright © <span id="year">2026</span> Unique Care</span><a href="../book-an-appointment/">Book an appointment</a></div></footer>
<a class="whatsapp" href="https://wa.me/919850644544" aria-label="Chat with Unique Care on WhatsApp"><img src="${A}whatsapp.png" alt=""></a>`;

function pageHero(eyebrow,title,copy,image,alt){const enhanced={'lab-interior.jpg':'lab-interior-hd.png','civil-hospital.webp':'civil-hospital-hd.png','mri.webp':'mri-hd.png'}[image]||image;return `<section class="inner-hero"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p>${copy}</p></div><img src="${A}${enhanced}" alt="${alt}"></section>`}
function cta(title='Ready to book your scan?'){return `<section class="section inner-cta page-section"><div><p class="eyebrow">We are here to help</p><h2>${title}</h2><p>Choose your nearest centre and send us your appointment request.</p></div><a class="button" href="../book-an-appointment/">Make An Appointment</a></section>`}
function serviceCards(){return `<div class="inner-service-grid"><article><img src="${A}mri-service.jpg" alt="MRI scan service"><div><p class="eyebrow">Digital 3T MRI</p><h2>Wide-bore MRI scanning</h2><p>Magnetic resonance imaging uses a magnetic field and radio waves to create detailed images of organs and tissues.</p><a class="text-link" href="../mri-scan/">Learn about MRI</a></div></article><article><img src="${A}ct-service.jpg" alt="CT scan service"><div><p class="eyebrow">128 Slice CT</p><h2>Fast, detailed CT imaging</h2><p>Computed tomography combines X-rays and computer technology to show bones, muscles, organs and blood vessels.</p><a class="text-link" href="../ct-scan/">Learn about CT</a></div></article></div>`}

function locationPage(data){return `${pageHero('Unique Care '+data.name,data.name+' diagnostic imaging centre',data.address,data.image,'Unique Care '+data.name+' centre')}<section class="section location-contact page-section"><div><p class="eyebrow">Centre details</p><h2>Visit Unique Care ${data.name}</h2><p>${data.address}</p></div><div><p class="eyebrow">Call the centre</p>${data.phones.map(phone=>`<a href="tel:${phone.replace(/\s/g,'')}">${phone}</a>`).join('')}</div></section><section class="section page-section"><div class="inner-heading"><p class="eyebrow">Services at this centre</p><h2>Advanced imaging with patient-first support.</h2></div>${serviceCards()}</section><section class="patient-guide"><div class="section"><div><p class="eyebrow">Before your visit</p><h2>Come prepared for a smoother appointment.</h2></div><ol><li><b>01</b><span>Bring your doctor's prescription and previous scan reports.</span></li><li><b>02</b><span>Confirm any preparation instructions with the centre.</span></li><li><b>03</b><span>Arrive a little early for registration and safety screening.</span></li></ol></div></section>${cta('Book your scan at '+data.name)}`}

const pages = {
  'about-us': `${pageHero('About Unique Care','Advanced technology.<br>Care centred on people.','Unique Care brings modern MRI and CT imaging closer to communities across Maharashtra.','lab-interior.jpg','Unique Care diagnostic imaging facility')}<section class="section story-grid page-section"><div><p class="eyebrow">Our approach</p><h2>Precise imaging, delivered with clarity and respect.</h2></div><div><p>We believe advanced diagnostic technology is most valuable when patients feel informed and supported. Our centres combine high-quality imaging systems with teams focused on comfort, communication and efficient service.</p><p>With centres in Ratnagiri, Satara, Alibaug, Thane and Pune Aundh, we work to improve access to MRI and CT services across the region.</p></div></section><section class="values-section"><div class="section"><p class="eyebrow">What guides us</p><div class="value-grid"><article><span>01</span><h2>Accuracy</h2><p>Advanced equipment and careful imaging workflows.</p></article><article><span>02</span><h2>Access</h2><p>Government service in the morning and private service in the evening.</p></article><article><span>03</span><h2>Comfort</h2><p>Wide-bore MRI and thoughtful support throughout the scan.</p></article><article><span>04</span><h2>Clarity</h2><p>Helpful guidance before, during and after your visit.</p></article></div></div></section><section class="section technology-story page-section"><img src="${A}mri-omega.webp" alt="uMR Omega MRI system"><div><p class="eyebrow">Our technology</p><h2>Built for detailed imaging and a better patient experience.</h2><p>The uMR Omega ultra-wide bore MRI combines a spacious 75 cm bore, fast imaging technology and consistent image quality to expand access without compromising care.</p><a class="text-link" href="../mri-scan/">Explore MRI technology</a></div></section>${cta()}`,
  services: `${pageHero('Our services','Imaging answers<br>your care team can trust.','MRI and CT scanning supported by advanced technology, patient guidance and convenient centre access.','ct-scan.webp','CT scanner at Unique Care')}<section class="section page-section"><div class="inner-heading"><p class="eyebrow">MRI & CT scans</p><h2>Two advanced imaging services. One standard of care.</h2></div>${serviceCards()}</section><section class="patient-guide"><div class="section"><div><p class="eyebrow">Your journey</p><h2>Simple steps, support at every stage.</h2></div><ol><li><b>01</b><span>Book your preferred centre and service time.</span></li><li><b>02</b><span>Follow the preparation guidance for your scan.</span></li><li><b>03</b><span>Complete your scan with help from our care team.</span></li><li><b>04</b><span>Receive your report for the next step in care.</span></li></ol></div></section><section class="section service-benefits page-section"><article><h2>Wide-bore comfort</h2><p>A more spacious MRI environment designed to reduce anxiety.</p></article><article><h2>Detailed imaging</h2><p>High-quality MRI and CT scans for a wide range of clinical needs.</p></article><article><h2>Convenient access</h2><p>Five centres with clearly separated government and private service times.</p></article></section>${cta()}`,
  testimonial: `${pageHero('Patient experiences','Trust built through<br>every interaction.','Read what patients say about our people, facilities and diagnostic services.','lab-interior.jpg','Unique Care patient facility')}<section class="section ratings-summary page-section"><div><strong>4.7</strong><span>Average patient rating</span></div><p>Patients regularly mention helpful staff, clean facilities, professional service and timely reports.</p></section><section class="section review-wall page-section"><article><p>5.0 rating</p><blockquote>“Wonderful experience. Fast service. Ashish was helpful at the desk.”</blockquote><strong>Rakesh Mittal</strong></article><article><p>5.0 rating</p><blockquote>“Highly professional and genuinely warm individuals. I highly recommend Unique Care.”</blockquote><strong>Shishankaa Wangnoo</strong></article><article><p>5.0 rating</p><blockquote>“Very clean and tidy lab. Staff are professional and the report was given on time.”</blockquote><strong>Gaurav Chakraborty</strong></article><article><p>5.0 rating</p><blockquote>“A one-stop shop for diagnostic needs. Well equipped and an excellent experience.”</blockquote><strong>Murali Sundaram</strong></article><article><p>5.0 rating</p><blockquote>“Very proactive staff and hospital professionals with world-class instruments under one roof.”</blockquote><strong>Mayuri Kadam</strong></article><article><p>5.0 rating</p><blockquote>“Very professional and polite staff. Competitive prices with quality services.”</blockquote><strong>Yashraj Bais</strong></article></section>${cta('Experience patient-first imaging care')}`,
  'contact-us': `${pageHero('Contact Unique Care','Find the centre<br>closest to you.','Call a centre directly or send an appointment request and our team will help you with the next step.','civil-hospital.webp','Unique Care hospital location')}<section class="section all-locations page-section"><div class="inner-heading"><p class="eyebrow">Our centres</p><h2>Five locations across Maharashtra.</h2></div><div class="contact-location-grid">${Object.entries(locations).map(([slug,data])=>`<article><h2>${data.name}</h2><p>${data.address}</p>${data.phones.map(phone=>`<a href="tel:${phone.replace(/\s/g,'')}">${phone}</a>`).join('')}<a class="text-link" href="../${slug}/">View centre</a></article>`).join('')}</div></section>${cta('Need help choosing a centre?')}`,
  'mri-scan': `${pageHero('Digital 3T MRI scan','Access.<br>Uncompromised.','The uMR Omega ultra-wide bore MRI is designed for detailed imaging, faster exams and a more comfortable patient experience.','mri-banner.webp','uMR Omega MRI scanner')}<section class="section scan-intro page-section"><div><p class="eyebrow">Ultra-wide bore MRI</p><h2>Greater access for your community.</h2><p>The spacious environment created by the 75 cm bore is accentuated by a calming starlight system and a design focused on patient comfort.</p></div><img src="${A}mri-omega.webp" alt="uMR Omega MRI scanner"></section><section class="scan-benefits"><div class="section"><article><span>01</span><h2>Faster exams</h2><p>AI-assisted imaging technology can shorten exam times while maintaining high-resolution imaging.</p></article><article><span>02</span><h2>Patient comfort</h2><p>The ultra-wide bore and spacious environment support a calmer scan experience.</p></article><article><span>03</span><h2>Consistent images</h2><p>High homogeneity and powerful gradients support consistently detailed image quality.</p></article></div></section><section class="section innovation page-section"><div class="inner-heading"><p class="eyebrow">Founded on innovation</p><h2>Technology designed to deliver.</h2></div><div class="innovation-grid"><article><img src="${A}innovation-easyscan.webp" alt="EasyScan MRI workflow"><h2>Easy scanning</h2><p>Workflow tools help technologists work efficiently and consistently.</p></article><article><img src="${A}innovation-coils.webp" alt="MRI coil technology"><h2>Advanced coils</h2><p>Flexible technology supports imaging across different body areas.</p></article><article><img src="${A}innovation-magnet.webp" alt="MRI magnet technology"><h2>Powerful platform</h2><p>A high-performance imaging platform built for current and future needs.</p></article></div></section><section class="section faq-section page-section"><div><p class="eyebrow">Patient questions</p><h2>Before your MRI scan.</h2></div><div>${faq('What should I bring?','Bring your doctor’s prescription, identification and any previous relevant reports or scans.')}${faq('How should I prepare?','Preparation depends on the scan. Confirm instructions with your selected centre before the appointment.')}${faq('What about metal implants?','Tell the team about implants, devices, surgery or metal in your body before entering the MRI area.')}${faq('Can I ask questions?','Yes. Our team will explain the process and help you feel prepared before the scan begins.')}</div></section>${cta('Book your MRI scan')}`,
  'ct-scan': `${pageHero('128 Slice CT scan','Fast imaging.<br>Detailed answers.','Computed tomography combines a series of X-ray images with computer processing to create detailed cross-sectional views of the body.','ct-scan.webp','128 slice CT scanner')}<section class="section scan-intro page-section"><div><p class="eyebrow">Computerized tomography</p><h2>Detailed imaging when speed matters.</h2><p>CT scans can provide more detailed information than plain X-rays and are used to visualize bones, blood vessels, soft tissues and internal organs.</p></div><img src="${A}supria.webp" alt="Supria CT scanner"></section><section class="scan-benefits"><div class="section"><article><span>01</span><h2>Diagnose</h2><p>Helps identify muscle and bone disorders, infections, blood clots and other conditions.</p></article><article><span>02</span><h2>Guide</h2><p>Supports procedures such as surgery, biopsy and radiation therapy planning.</p></article><article><span>03</span><h2>Monitor</h2><p>Helps care teams monitor disease, treatment response and internal injuries.</p></article></div></section><section class="section faq-section page-section"><div><p class="eyebrow">Patient questions</p><h2>Before your CT scan.</h2></div><div>${faq('What should I bring?','Bring your doctor’s prescription, identification and previous relevant scan reports.')}${faq('Will I need contrast?','Some CT exams use contrast for greater detail. Your doctor and the scan team will advise you.')}${faq('How long does it take?','The scan itself is usually fast, but preparation time varies with the type of examination.')}${faq('How should I prepare?','Ask the selected centre about food, drink, medicines and any specific preparation instructions.')}</div></section>${cta('Book your CT scan')}`,
  'book-an-appointment': `${pageHero('Appointments','Book your scan<br>with confidence.','Send your details and selected centre. Our team will contact you to help confirm the appointment.','mri-service.jpg','Patient being prepared for an MRI scan')}<section class="appointment-wrap"><div class="appointment-support"><p class="eyebrow">Get a callback</p><h2>We will help with the next step.</h2><p>Complete the form with your preferred location. If you have a prescription, you can add it before submitting.</p><div><strong>Morning</strong><span>Government Service</span></div><div><strong>Evening</strong><span>Private Service</span></div></div><div class="appointment-card"><form class="appointment-form" action="https://docs.google.com/forms/u/1/d/e/1FAIpQLSfxM09LHhUOYkoXTXUA0jGk6otyid7JZLBWwiP1RsH6weOsKA/formResponse" method="post" target="appointment-response"><div class="patient-fields"><label class="form-field">Patient Name <span class="required">*</span><input type="text" name="entry.513324995" required autocomplete="name"></label><label class="form-field">Patient Mobile No <span class="required">*</span><input type="tel" name="entry.1550174705" required autocomplete="tel"></label></div><fieldset class="location-group"><legend>Select Location <span class="required">*</span></legend><div class="location-options">${['Ratnagiri','Satara','Alibaug','Thane','Pune Aundh'].map(name=>`<label class="location-option"><input type="radio" name="entry.381216950" value="${name}" required><span>${name}</span></label>`).join('')}</div></fieldset><label class="upload-field">Upload doctor prescription <span class="file-button">Choose file<input class="prescription-file" type="file" accept="image/*,.pdf"></span><span class="file-name">No file selected</span></label><button class="appointment-submit" type="submit">Submit appointment request</button><p class="appointment-status" aria-live="polite"></p></form><iframe class="response-frame" name="appointment-response" title="Appointment form response"></iframe></div></section>`
};

function faq(question,answer){return `<article class="faq-item"><button class="faq-question" type="button" aria-expanded="false">${question}<span>Show answer</span></button><p>${answer}</p></article>`}

const content = locations[page] ? locationPage(locations[page]) : pages[page] || `<section class="section missing-page"><h1>Page not found</h1><a class="button" href="../">Return home</a></section>`;
document.body.insertAdjacentHTML('afterbegin', header);
document.body.insertAdjacentHTML('beforeend', `<main id="content" class="inner-main">${content}</main>${footer}`);

if (!document.querySelector('link[href="../animations.css"]')) {
  const animationStyles = document.createElement('link'); animationStyles.rel='stylesheet'; animationStyles.href='../animations.css'; document.head.append(animationStyles);
}
if (page === 'book-an-appointment' && !document.querySelector('link[href="../appointment.css"]')) {
  const appointmentStyles = document.createElement('link'); appointmentStyles.rel='stylesheet'; appointmentStyles.href='../appointment.css'; document.head.append(appointmentStyles);
}
